# Welcome to Jekyll!
#

# Site settings
title: Skylabs
description: |
  Skylabs invites you to witness nature’s biggest spectacle: <br>
  The universe itself! <br>
  Join us under the stars for a night of stargazing.
owner: Skylabs # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: skylabsnz@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://skylabsnz.github.io" # the base hostname & protocol for your site
social:
  pinterest: https://www.pinterest.nz/skylabsnz/
  facebook-official: https://www.facebook.com/skylabs.co.nz
  instagram: https://www.instagram.com/skylabsnz/
  github: https://github.com/skylabsnz
  #linkedin-square: https://linkedin.com/in/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
